# This file created by conda-build 25.4.2
# ------------------------------------------------

package:
  name: libstdcxx-ng
  version: 15.1.0
source:
  - patches:
      - patches/0002-allow-commands-in-main-specfile.patch
      - patches/0003-patch-zoneinfo_dir_override-to-point-to-our-tzdata.patch
      - patches/0004-add-ldl-to-libstdc___la_LDFLAGS.patch
      - patches/0005-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
    sha256: 51b9919ea69c980d7a381db95d4be27edf73b21254eb13d752a08003b4d013b1
    url: https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-15.1.0.tar.gz
build:
  number: 2
  run_exports:
    strong:
      - libstdcxx
  string: h4852527_2
requirements:
  host:
    - libstdcxx 15.1.0 h8f9b012_2
  run:
    - libstdcxx 15.1.0 h8f9b012_2
test:
  commands:
    - echo "empty wrapper for compatibility with previous naming"
about:
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GNU C++ Runtime Library
extra:
  copy_test_source_files: true
  feedstock-name: ctng-compilers-feedstock
  final: true
  flow_run_id: azure_20250507.2.1
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
  remote_url: https://github.com/conda-forge/ctng-compilers-feedstock
  sha: f39ac1e45bd93e4f46a1402dd14ac3e6dc703167
